{
 "title": "Iot Datos Historicos",
 "time": { "from": "2022-04-28T17:53:11.968Z", "to": "2022-04-28T18:05:37.000Z" },
 "panels": [
  {
   "title": "Temperatura y humedad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH\n  constantes (temperatura, humedad) AS (values(1, 2)),\n  time_p AS (SELECT d.time, t.idx as index, t.time + cast(extract(epoch from d.base_time) as integer) as tiempo FROM processor_data as d, constantes as c LEFT JOIN UNNEST(d.times) WITH ORDINALITY AS t(time, idx) ON TRUE WHERE d.measurement_id = c.temperatura) ,\n  value_p AS (SELECT d.time, v.idx as index, v.value as valor FROM processor_data as d, constantes as c LEFT JOIN UNNEST(d.values) WITH ORDINALITY AS v(value, idx) ON TRUE WHERE d.measurement_id = c.temperatura)\nSELECT t.tiempo as time, v.valor as temperatura FROM time_p t LEFT JOIN value_p v on (t.time = v.time AND t.index = v.index);"
    },
    {
     "rawSql": "WITH\n  constantes (temperatura, humedad) AS (values(1, 2)),\n  time_p AS (SELECT d.time, t.idx as index, t.time + cast(extract(epoch from d.base_time) as integer) as tiempo FROM processor_data as d, constantes as c LEFT JOIN UNNEST(d.times) WITH ORDINALITY AS t(time, idx) ON TRUE WHERE d.measurement_id = c.humedad) ,\n  value_p AS (SELECT d.time, v.idx as index, v.value as valor FROM processor_data as d, constantes as c LEFT JOIN UNNEST(d.values) WITH ORDINALITY AS v(value, idx) ON TRUE WHERE d.measurement_id = c.humedad)\nSELECT t.tiempo as time, v.valor as humedad FROM time_p t LEFT JOIN value_p v on (t.time = v.time AND t.index = v.index);"
    }
   ]
  },
  {
   "title": "Humedad Actual",
   "type": "gauge",
   "description": "Gráfico gauge que mide respecto a un máximo y mínimo histórico el último valor recibido de humedad ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH\n  constantes (temperatura, humedad) AS (values(1, 2)),\n  time_p AS (SELECT d.time, t.idx as index, t.time + cast(extract(epoch from d.base_time) as integer) as tiempo FROM processor_data as d, constantes as c LEFT JOIN UNNEST(d.times) WITH ORDINALITY AS t(time, idx) ON TRUE WHERE d.measurement_id = c.humedad) ,\n  value_p AS (SELECT d.time, v.idx as index, v.value as valor FROM processor_data as d, constantes as c LEFT JOIN UNNEST(d.values) WITH ORDINALITY AS v(value, idx) ON TRUE WHERE d.measurement_id = c.humedad)\nSELECT v.valor as humedad FROM time_p t LEFT JOIN value_p v on (t.time = v.time AND t.index = v.index);"
    }
   ]
  },
  {
   "title": "Temperatura actual",
   "type": "gauge",
   "description": "Gráfico gauge que mide respecto a un máximo y mínimo histórico el último valor recibido de temperatura",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH\n  constantes (temperatura, humedad) AS (values(1, 2)),\n  time_p AS (SELECT d.time, t.idx as index, t.time + cast(extract(epoch from d.base_time) as integer) as tiempo FROM processor_data as d, constantes as c LEFT JOIN UNNEST(d.times) WITH ORDINALITY AS t(time, idx) ON TRUE WHERE d.measurement_id = c.temperatura) ,\n  value_p AS (SELECT d.time, v.idx as index, v.value as valor FROM processor_data as d, constantes as c LEFT JOIN UNNEST(d.values) WITH ORDINALITY AS v(value, idx) ON TRUE WHERE d.measurement_id = c.temperatura)\nSELECT v.valor as temperatura FROM time_p t LEFT JOIN value_p v on (t.time = v.time AND t.index = v.index);"
    }
   ]
  },
  {
   "title": "Humedad",
   "type": "geomap",
   "description": "Mapa que permite visualizar la información de los nodos y la humedad\nTamaño representa la cantidad de nodos tomando información en ese punto\nColor representa el valor de la humedad respecto a los máximos y mínimos definidos",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT sta.location_id, sta.quantity, sta.value, location.lat as latitude, location.lng as longitude from ( SELECT station.location_id, COUNT(*) as quantity, AVG(data.value) as value from (SELECT station_id, AVG(avg_value) as value from processor_data WHERE measurement_id = 2 group by station_id) data RIGHT JOIN processor_station station on (data.station_id = station.id) group by station.location_id) sta RIGHT JOIN processor_location location on (sta.location_id = location.id);"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "geomap",
   "description": "Mapa que permite visualizar la información de los nodos y la temperatura\nTamaño representa la cantidad de nodos tomando información en ese punto\nColor representa el valor de la temperatura respecto a los máximos y mínimos definidos",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT sta.location_id, sta.quantity, sta.value, location.lat as latitude, location.lng as longitude \nfrom \n( SELECT station.location_id, COUNT(*) as quantity, AVG(data.value) as value \nfrom (SELECT station_id, AVG(avg_value) as value from processor_data \nWHERE measurement_id = 1 group by station_id) data \nRIGHT JOIN processor_station station on (data.station_id = station.id) \ngroup by station.location_id) sta RIGHT JOIN processor_location location on (sta.location_id = location.id);"
    }
   ]
  }
 ]
}