# Generated by Django 3.2.4 on 2021-06-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtimeGraph', '0002_auto_20210616_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='type',
            new_name='variable',
        ),
    ]
