# Generated by Django 3.2.4 on 2021-06-16 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtimeGraph', '0003_rename_type_sensor_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='sensor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='realtimeGraph.sensor'),
        ),
    ]
