# Generated by Django 3.2.4 on 2021-06-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtimeGraph', '0004_sensordata_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='ssdsds', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
